version: "3"

services:
  db:
    image: postgres:13.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks: 
      - back-tier
      - result-tier
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:buster
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier

  worker:
      build: ./worker/
      restart: always
      depends_on:
        - redis
        - db
      environment:
        - 0.0.0.0
      networks:
        - back-tier

  result:
      build: ./result/
      restart: always
      depends_on:
        - db
      environment:
        - 0.0.0.0
      ports:
        - 5001:80
      networks:
        - result-tier

  poll:
    build: ./poll/
    restart: always
    links:
      - redis
      - db
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
    ports: 
      - 5000:80
    networks: 
      - poll-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
